### ISSUE TITLE
documentation about the results seems to be incorrect

### ISSUE THREAD

**Issue by gainxglobal** [Kikobeats/hyperdiff#9]
I'm exactly sure how to interpret the documentation for the `dist` parameter. It reads:

"Second array for be compared. Notes the results are modeled from the second array."

For the following example:

```
  const diff = require('hyperdiff')
  const result = diff(
    [
      {id: 1, name: 'a1'},
      {id: 2, name: 'b'},
      {id: 3, name: 'c'},
      {id: 4, name: 'd'},
      {id: 5, name: 'e'}
    ],
    [
      {id: 1, name: 'a2'},
      {id: 2, name: 'b'},
      {id: 7, name: 'e'}
    ],
    ['id']
  );
```

I would expect `result.common` to be:
`[ { id: 1, name: 'a2' }, { id: 2, name: 'b' } ]`

The actual result is:
`[ { id: 1, name: 'a1' }, { id: 2, name: 'b' } ]`

The statement "Notes the results are modeled from the second array" would lead me to think this way.

**Comment by Kikobeats** [comment]
I think the result is correct.

The `second` collection is like an evolution of the `first` collection over the time.

From this perspective:

- `{id: 7, name: 'e'}` was added (present at `second` and not at `first`)
- Both have `{id:1}` and `{id:2}` at common. Notes that you are specifing as third argument that just use `id` as comprator, so the value of  `name` is not relevant.
- The rest are considered are removed because are present at `second` anymore.
